CREATE TABLE RELATIONSHIP(
  USER_FROM_ID         BIGINT NOT NULL,
  USER_TO_ID           BIGINT NOT NULL,
  PRIMARY KEY(USER_FROM_ID,USER_TO_ID),
  STATUS               VARCHAR(50) CHECK(STATUS = 'REQUESTED' OR STATUS = 'REJECTED' OR STATUS = 'ACCEPTED' OR STATUS = 'DELETED'));
