CREATE TABLE RELATIONSHIP(
  ID                   BIGINT PRIMARY KEY,
  USER_FROM_ID         BIGINT NOT NULL,
  USER_TO_ID           BIGINT NOT NULL,
  STATUS               VARCHAR(50) CHECK(STATUS = 'REQUESTED' OR STATUS = 'REJECTED' OR STATUS = 'ACCEPTED' OR STATUS = 'NOT_FRIENDS'));
