CREATE TABLE MESSAGE(
 ID           BIGINT PRIMARY KEY,
 TEXT         VARCHAR(140) NOT NULL,
 DATE_SENT    DATE NOT NULL,
 DATE_EDITED  DATE,
 DATE_DELETED DATE,
 DATE_READ    DATE,
 USER_FROM_ID BIGINT REFERENCES USER_TABLE(ID),
 USER_TO_ID BIGINT REFERENCES USER_TABLE(ID));