CREATE TABLE MESSAGE(
 ID           BIGINT PRIMARY KEY,
 TEXT         VARCHAR(250) NOT NULL,
 DATE_SENT    DATE NOT NULL,
 DATE_READ    DATE,
 ID_USER_FROM BIGINT REFERENCES USER_TABLE(ID),
 ID_USER_TO BIGINT REFERENCES USER_TABLE(ID));