CREATE TABLE MESSAGE(
 ID           NUMBER PRIMARY KEY,
 TEXT         VARCHAR(250) NOT NULL,
 DATE_SENT    DATE NOT NULL,
 DATE_READ    DATE NOT NULL,
 FOREIGN KEY(ID_USER_FROM) REFERENCES USER(ID),
 FOREIGN KEY(ID_USER_TO) REFERENCES USER(ID)
);