CREATE TABLE POST(
  ID           BIGINT PRIMARY KEY,
  TEXT         VARCHAR(200) NOT NULL,
  DATE_POSTED  DATE NOT NULL,
  LOCATION     VARCHAR(250),
  USER_POSTED_ID  BIGINT,
  FOREIGN KEY(USER_POSTED_ID) REFERENCES USER_TABLE(ID),
  USER_PAGE_ID  BIGINT,
  FOREIGN KEY(USER_PAGE_ID) REFERENCES USER_TABLE(ID);